config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'home', to: 'pages#home'
  get 'sign_in_session', to: 'pages#sign_in_session'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end

  resources :orders, only: [:create] do
    member do
      get :checkout
    end
    collection do
      post :pay
    end
  end

  resources :events, only: [] do
    resources :products, only: [] do
      get :buy
    end
  end

  resources :events do
    resources :event_products, only: [:destroy]
    member do
      patch :add_gift
    end
  end

  resources :events do
    member do
      get :stores, to: 'stores#index', as: 'stores'
    end
  end

  resources :events, only: [] do
    resources :stores, only: [] do
      resources :products
    end
  end

  resources :stores do
    resources :products
    member do
      get :orders, to: 'stores#orders'
    end
  end
end

app/models/store.rb
class Store < ApplicationRecord
  acts_as_paranoid

  # relation
  belongs_to :user
  has_many :orders
  has_many :products, dependent: :destroy
  has_one_attached :avatar
  
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
before_action :find_store, only: %i[update edit destroy show]
before_action :authenticate_user!
  def index
    if current_user?
      @q = Store.ransack(params[:q])
      @store = @q.result
      if params[:id]
        @event = Event.find(params[:id])
      elsif params[:q]
        @event = Event.find(params[:q][:event].to_i)
      end

    elsif current_user_store?
      @store = current_user.store
      redirect_to store_products_path(@store.id)
    else
      redirect_to new_store_path
    end
  end

  def new
    @store = Store.new
  end

  def create
    @store = current_user.build_store(store_params) if current_vendor?
    if @store.save
      redirect_to stores_path, notice: '成功新增商店！'
    else
      render :new
    end
  end

  def show
    if current_user_store?
      @store = current_user.store
      redirect_to store_products_path(@store.id)
    else
      redirect_to new_store_path
    end
  end

  def edit; end

  def update
    if @store.update(store_params)
      redirect_to stores_path, notice: '成功更新商店！'
    else
      render :edit
    end
  end

  def destroy
    @store.destroy

    redirect_to stores_path, alert: '商店已刪除'
  end

  def orders
    @orders = current_user.store.orders
  end

  private

  def store_params
    params.require(:store).permit(:title, :description, :avatar)
  end

  def find_store
    @store = Store.find_by(id: params[:store_id])
    return unless current_user_store?
    @store = current_user.store
  end

  def current_user_store?
    @store = current_user.store
  end
end

app/views/stores/edit.html.erb
<section class="flex flex-wrap items-center justify-center gap-16 h-screen -mt-16 pt-20 ">
  <div class="container px-6 pt-14 mx-auto flex items-center justify-center lg:h-full ">
    <div class="flex pb-3 justify-center items-center  flex-wrap g-6 text-gray-800 ">
      <div class=" md:col-span-2 ">
        <%= form_with model:@store do |f| %>
          <div class="shadow-xl overflow-hidden rounded-md ">
            <div class="px-4 py-3 bg-theme_light_purple text-right sm:px-6 flex justify-center rounded-t">
              <h1 class=" text-white text-2xl font-bold leading-tight tracking-tight text-center  md:text-3xl dark:text-white ">
                編 輯 商 店
              </h1>
            </div>
            <div class="px-4 py-5 bg-white sm:p-6">
              <div class="grid grid-cols-6 gap-6 ">
                <div class="col-span-6 sm:col-span-3 ">
                  <%= f.label :title, '商店名稱', autofocus: true, 
                  class:"block mb-2 text-base font-medium text-gray-900 dark:text-white" %>
                  <%= f.text_area :title, class: " resize-none bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" , autofocus: true , require: true%>
                  
                  <div class="mt-3">
                    <%= f.label :description, '商店描述', class:"block mb-2 text-base font-medium text-gray-900 dark:text-white"  %>
                    <%= f.text_area :description  ,class: "resize-none bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder: "寫下商店描述，讓大家更認識你的商店吧！", require: true %>
                  </div>
                  <div class="col-span-6 sm:col-span-3 pt-6 ">
                    <%=f.label :avatar,"更換圖片（無需更換請點擊完成編輯）", class: "block mb-2 text-base font-medium text-gray-900 dark:text-white"%>
                    <%=f.file_field :avatar, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"%>
                  </div>    
                </div>
                <div class=" col-span-6 sm:col-span-3 flex">
                  <%= image_tag url_for(@store.avatar), width: 300, height: 300, class: 'rounded mx-auto items-center' if @store.avatar.attached? %>
                </div>
                <div class=" col-span-6 sm:col-span-3">
              </div>
            </div>
            <div class="px-4 py-3 text-right sm:px-6 flex justify-center">
              <button type="submit" class="theme-button">
                完 成 編 輯
              </button>
            </div>
          </div>
        <% end  %>
      </div>
    </div>
  </div>
</section>

app/views/stores/index.html.erb
<h1 class="pt-14 text-3xl font-bold leading-tight tracking-tight text-center text-theme_text4 md:text-3xl dark:text-white mb-5">
  商店總覽
</h1>
<!-- search bar -->
<div class="md:w-1/4 sm:w-3/4 mx-auto mb-6">
  <%= search_form_for @q  do |f| %>
    <div class="relative">
      <%= f.hidden_field :event, value: @event.id%>
      <%= f.search_field :title_cont, class: "block w-full p-4 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder:"搜尋商店", autofocus: true%>
      <button id="search-btn" type="submit" class="absolute right-2 bottom-1 theme-button ">
        搜尋
      </button>
    </div>
  <% end %>
</div>
<!-- store card list -->
<div class=" mx-auto flex gap-10 flex-wrap justify-center px-3 pt-8  pb-3">
  <%@store.each do |store| %>
    <%=link_to event_store_products_path(@event,store) do%> 
      <div class="bg-white shadow-md border-gray-200 rounded-lg w-72">
        <%= image_tag store.avatar, class: "rounded align-center img-fixed" if store.avatar.attached?%>
        <h1 class="text-center text-theme_text5 font-bold text-2xl tracking-tight mb-2 pt-3 break-words px-5">

          <%=store.title%>
        </h1>
        <p class="text-lg text-theme_text5 pb-8 px-5 break-words">
          <%=store.description%>
        </p>
      </div>
    <% end  %>
  <% end %>
</div>

app/views/stores/new.html.erb
<section class="flex flex-wrap items-center justify-center gap-16 h-screen -mt-16 pt-20 ">
  <div class="container px-6 pt-14 mx-auto flex items-center justify-center lg:h-full ">
    <div class="flex pb-3 justify-center items-center  flex-wrap g-6 text-gray-800 ">
      <div class=" md:col-span-2 ">
        <%= form_with model:@store do |f| %>
          <div class="shadow-xl overflow-hidden rounded-md ">
            <div class="px-4 py-3 bg-theme_light_purple text-right sm:px-6 flex justify-center rounded-t">
              <h1 class=" text-white text-2xl font-bold leading-tight tracking-tight text-center  md:text-3xl dark:text-white ">
                新 增 商 店
              </h1>
            </div>
            <div class="px-4 py-5 bg-white sm:p-6">
              <div class="grid grid-cols-6 gap-6 ">
                <div class="col-span-6 sm:col-span-3 ">
                  <%= f.label :title, content_tag(:span, "*", style: "color: red;") + '商店名稱', autofocus: true, 
                  class:"block mb-2 text-base font-medium text-gray-900 dark:text-white" %>
                  <%= f.text_area :title, class: " resize-none bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" , autofocus: true , require: true%>
                  <div class="col-span-6 sm:col-span-3 pt-6 ">
                    <%=f.label :avatar,content_tag(:span, "*", style: "color: red;") + "商店封面照片", class: "block mb-2 text-base font-medium text-gray-900 dark:text-white"%>
                    <%=f.file_field :avatar, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", required: true%>
                  </div>    
                </div>
  
                <div class=" col-span-6 sm:col-span-3">

                  <div class="mb-3">
                    <%= f.label :description,content_tag(:span, "*", style: "color: red;") +  '商店描述', class:"block mb-2 text-base font-medium text-gray-900 dark:text-white"  %>
                    <%= f.text_area :description , size: "20x10" ,class: "resize-none bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder: "寫下商店描述，讓大家更認識你的商店吧！", require: true %>
                  </div>
                </div>
                  
              </div>
            </div>
            <div class="px-4 py-3 bg-gray-50 text-right sm:px-6 flex justify-center">
              <button type="submit" class="theme-button">
                確 定 新 增
              </button>
            </div>
          </div>
        <% end  %>
      </div>
    </div>
  </div>
</section>

app/views/stores/orders.html.erb
<div class="flex flex-col">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full">
          <thead class="bg-white border-b">
            <tr>
              <th scope="col" class="text-xl font-medium text-gray-900 px-6 py-4 text-center">
                訂單編號
              </th>
              <th scope="col" class="text-xl font-medium text-gray-900 px-6 py-4 text-center">
                訂單金額
              </th>
              <th scope="col" class="text-xl font-medium text-gray-900 px-6 py-4 text-center">
                商品名稱
              </th>
              <th scope="col" class="text-xl font-medium text-gray-900 px-6 py-4 text-center">
                訂單狀態
              </th>
              <th scope="col" class="text-xl font-medium text-gray-900 px-6 py-4 text-center">
                商品數量
              </th>
              <th scope="col" class="text-xl font-medium text-gray-900 px-6 py-4 text-center">
                寄送地址
              </th>
              <th scope="col" class="text-xl font-medium text-gray-900 px-6 py-4 text-center">
                收貨人
              </th>
              <th scope="col" class="text-xl font-medium text-gray-900 px-6 py-4 text-center">
                收貨人聯絡電話
              </th>
            </tr>
          </thead>
          <tbody>
          <% @orders.each do |order| %>
            <tr class="bg-white border-b transition duration-300 ease-in-out hover:bg-gray-100">
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 text-center"><%= order.serial%></td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap text-center">
                <%= order.price %>
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap text-center">
                <%= order.product.name %>
              </td>
              <% if order.state == 'paid' %>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap text-center">
              已付款
              </td>
              <% else %>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap text-center">
              尚未完成付款
              </td>
              <% end %>  
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap text-center">
                <%= order.sold_quantity %>
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap text-center">
                <%= order.address %>
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap text-center">
                <%= order.receiver %>
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap text-center">
                <%= order.phone %>
              </td>
            </tr>
          <% end %> 
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/stores/show.html.erb
<h1 class="pt-20">訂單確認頁面</h1>

<table>
  <tr>
    <td></td>
    <td>訂單編號</td>
    <td>商品項目</td>
    <td>購買數量</td>
    <td>銷售金額</td>
  </tr>

  <tr>
    <% @paid_orders.each do |paid_order| %>
      <td>
        <%= paid_order.serial %>
      </td>
      <td>
        <%= paid_order.price %>
      </td>
      <td>
        <%= paid_order.sold_quantity %>
      </td>
      <% end %>
  </tr>
</table>

app/views/stores/show_order.html.erb
<h1 class="pt-20">訂單確認頁面</h1>
<table class="mt-3">
  <tr>
    <td>訂單編號</td>
    <td>商品名稱</td>
    <td>購買數量</td>
    <td>銷售金額</td>
    <td>收件地址</td>
    <td>收件人</td>
    <td>收件聯絡人電話</td>
  </tr>
    <% @paid_orders.each do |paid_order| %>
    <tr>
      <td class="text-center">
        <%= paid_order.serial %>
      </td>
      <td class="text-center">
        <%= paid_order.product.name %>
      </td>
      <td class="text-center">
        <%= paid_order.sold_quantity %>
      </td>
      <td class="text-center">
        <%= paid_order.price %>
      </td>
      <td class="text-center">
        <%= paid_order.address %>
      </td>
      <td class="text-center">
        <%= paid_order.receiver %>
      </td>
      <td class="text-center">
        <%= paid_order.phone %>
      </td>
    </tr>
    <% end %>

</table>