config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'home', to: 'pages#home'
  get 'sign_in_session', to: 'pages#sign_in_session'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end

  resources :orders, only: [:create] do
    member do
      get :checkout
    end
    collection do
      post :pay
    end
  end

  resources :events, only: [] do
    resources :products, only: [] do
      get :buy
    end
  end

  resources :events do
    resources :event_products, only: [:destroy]
    member do
      patch :add_gift
    end
  end

  resources :events do
    member do
      get :stores, to: 'stores#index', as: 'stores'
    end
  end

  resources :events, only: [] do
    resources :stores, only: [] do
      resources :products
    end
  end

  resources :stores do
    resources :products
    member do
      get :orders, to: 'stores#orders'
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord

  acts_as_paranoid
  
  belongs_to :user

  validates_presence_of :title,:subtitle,:description,:venue,:receiver,:address,:start_at,:end_at
  validates :phone, numericality: true
  validate :start_date_after_end_date 

  # relation
  has_one_attached :avatar
  has_many :event_products, dependent: :destroy
  has_many :products, through: :event_products

  private
  def start_date_after_end_date
    if start_at < Time.current || end_at < start_at
      errors.add(:start_at,message:"開始時間不能小於現在時間，或者開始日期不能大於結束日期")
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_event, only: %i[show edit update destroy index add_gift]
  before_action :find_product, only: %i[add_gift remove_gift]
  before_action :authenticate_user!

  def index
    @events = current_user.events.all
  end

  def add_gift
    if @event.products.include?(@product)
      @event.products.delete(@product)
      render json: { status: 'deleted' }
    else
      @event.products << @product
      render json: { status: 'created' }
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params) if current_user?
    if @event.save
      redirect_to events_path, notice: '活動建立成功!'
    else
      render :new
    end
  end

  def show
    @event_products = @event.products.all
    @event = Event.find(params[:id])
    @product_paid = Order.where({ event_id: params[:id], state: 'paid' }).pluck(:product_id)
  end

  def edit; end

  def update
    if @event.update(event_params)
      redirect_to events_path, notice: '活動更新成功!'
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice: '成功刪除活動!'
  end

  private

  def event_params
    params.require(:event).permit(:title, :subtitle, :description, :start_at, :end_at, :venue, :avatar, :address,
                                  :phone, :receiver)
  end

  def find_event
    @event = Event.find_by(id: params[:id])
  end

  def find_product
    @product = Product.find(params[:product_id])
  end
end

app/views/events/edit.html.erb
      <section class="h-full pt-5">
        <div class=" pb-5 container px-6 pt-14 mx-auto flex items-center justify-center lg:h-full ">
          <div class="flex justify-center items-center flex-wrap g-6 text-gray-800 ">
            <div class="mt-5 md:mt-0 md:col-span-2">
              <%= form_for @event  do |form| %>
                <div class="shadow-xl overflow-hidden rounded-md ">
                  <div class="px-4 py-3 bg-theme_light_purple text-right sm:px-6 flex justify-center">
                    <h1 class=" text-white text-2xl font-bold leading-tight tracking-tight text-center  md:text-3xl dark:text-white ">
                      編 輯 活 動
                    </h1>
                  </div>
                  <div class="px-4 py-5 bg-white sm:p-6 flex">
                    <div class="grid grid-cols-6 gap-6 ">
                      <div class="col-span-6 sm:col-span-3">
                        <%= form.label :title, '活動名稱', 
                        class:"block mb-2 text-base font-medium text-gray-900 dark:text-white" %>
                        <%= form.text_field :title, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", 
                        required: true , autofocus: true%>
                      </div>
        
                      <div class=" col-span-6 sm:col-span-3">
  
                        <div class="mb-3">
                          <%= form.label :subtitle, '副標題', class:"block mb-2 text-base font-medium text-gray-900 dark:text-white"  %>
                          <%= form.text_field :subtitle, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", 
                          required: true %>
                        </div>
                      </div>
        
                      <div class="col-span-6 sm:col-span-3">
                        <%= form.label :venue, '活動場地', class:" block mb-2 text-base font-medium text-gray-900 dark:text-white"%>
                        <%= form.text_area :venue, class: " resize-none bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", 
                        required: true %>
                      </div>                    
                      <div class="col-span-6 sm:col-span-3">
                        <%= form.label :description, '活動簡述' , class:"block mb-2 text-base font-medium text-gray-900 dark:text-white"%>
                        <%= form.text_area :description, class: "resize-none bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", 
                        required: true %>
                      </div>
        
                      <div class=" col-span-6 sm:col-span-3">
  
                        <div class="mb-3">
                          <%= form.label :start_at, '活動開始日期', class:"block mb-2 text-base font-medium text-gray-900 dark:text-white"%>
                          <%= form.datetime_field :start_at , class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", 
                          required: true %>
                        </div>
                      </div>                    
                      <div class=" col-span-6 sm:col-span-3">
  
                        <div class="mb-3">
                          <%= form.label :end_at, '活動結束日期', class:"block mb-2 text-base font-medium text-gray-900 dark:text-white"%>
                          <%= form.datetime_field :end_at, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", 
                          required: true %>
                        </div>
                      </div>
                      <div class="col-span-6 sm:col-span-3 items-center my-auto">
                        <%=form.label :address,"禮品收件地址", class: "block mb-2 text-base font-medium text-gray-900 dark:text-white"%>
                        <%=form.text_field :address , class: " bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" , require: true%>
                      </div>

                      <div class="col-span-6 sm:col-span-3 items-center my-auto">
                        <%=form.label :phone,"收件人電話", class: "block mb-2 text-base font-medium text-gray-900 dark:text-white"%>
                        <%=form.text_field :phone , class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" , require: true%>
                      </div>

                      <div class="col-span-6 sm:col-span-3 items-center ">
                        <%=form.label :receiver,"收件人姓名", class: "block mb-2 text-base font-medium text-gray-900 dark:text-white"%>
                        <%=form.text_field :receiver , class: "mb-8 bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" , require: true%>
                        <div class="col-span-6 sm:col-span-3 items-center ">
                          <%=form.label :avatar,"更換封面（無需更換請點擊完成編輯）", class: "block mb-2 text-base font-medium text-gray-900 dark:text-white"%>
                          <%=form.file_field :avatar , class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"%>
                        </div>
                      </div>
                      <div class="col-span-6 sm:col-span-3">
                        <%= image_tag url_for(@event.avatar), class: "img-fixed rounded mx-auto" if @event.avatar.attached? %>
                      </div>
                    </div>
                  </div>
                  <div class="px-4 py-3 bg-gray-50 text-right sm:px-6 flex justify-center">
                    <button type="submit" class="theme-button">
                      編 輯 完 成
                    </button>
                  </div>
                </div>
              <% end  %>
            </div>
          </div>
        </div>
      </section>

app/views/events/index.html.erb
<div class='container mx-auto flex justify-center flex-wrap pt-20 '>
    <h1 class=' text-center text-3xl font-bold text-theme_text4'>我的活動清單</h1>
    <div class='w-full flex justify-center my-3'>
      <%= link_to "新增活動", new_event_path , class:'theme-button' %>
    </div>
    <% @events.each do |event| %>
      <div class='flex justify-center content-center flex-wrap m-2 bg-white shadow-md border border-gray-200 rounded-lg max-w-sm dark:bg-gray-800 dark:border-gray-700 w-full md:max-w-xs min-w-xs pt-3'>
        
        <div>
          <%= image_tag url_for(event.avatar), class: "rounded align-center img-fixed" if event.avatar.attached?%>
        </div>
          <div class='w-full text-center text-xl font-bold my-3'>
            <%= event.title %>
          </div>
          <div class='w-full break-all mx-5'>
            &nbsp;<%= event.subtitle %>
          </div>
          <div class='w-full justify-center flex p-2'>
            <%= link_to '查看活動', event_path(event.id), class:'theme-button'%>
            <%= link_to '刪除活動' , event_path(event.id), method: 'DELETE' , data: {confirm: "你確定要刪除活動嗎?" } , class:'destroy-btn'%>
          </div>  
        </div>
      <% end %>
</div>

app/views/events/new.html.erb
      <% if @event.errors.any? %>
        <div class="mt-10 border text-center mx-3 p-2 text-base text-gray-800 bg-gray-100 rounded-lg dark:bg-gray-700 dark:text-gray-300 font-bold ">
          <ul class="block border-1 text-lg text-red-600 ">
            <% @event.errors.full_messages_for(:start_at).each do |msg| %>
              <li class=""><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <section class="h-full">
        <div class=" pb-5 container px-6 pt-14 mx-auto flex items-center justify-center lg:h-full ">
          <div class="flex justify-center items-center flex-wrap g-6 text-gray-800 ">
            <div class="mt-5 md:mt-0 md:col-span-2">
              <%= form_for @event  do |form| %>
                <div class="shadow-xl overflow-hidden rounded-md ">
                  <div class="px-4 py-3 bg-theme_light_purple text-right sm:px-6 flex justify-center">
                    <h1 class=" text-white text-2xl font-bold leading-tight tracking-tight text-center  md:text-3xl dark:text-white ">
                      新 增 活 動
                    </h1>
                  </div>
                  <div class="px-4 py-5 bg-white sm:p-6 flex">
                    <div class="grid grid-cols-6 gap-6 ">
                      <div class="col-span-6 sm:col-span-3">
                        <%= form.label :title, content_tag(:span, "*", style: "color: red;") + '活動名稱', 
                        class:"block mb-2 text-base font-medium text-gray-900 dark:text-white" %>
                        <%= form.text_field :title, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", 
                        required: true , autofocus: true%>
                      </div>
        
                      <div class=" col-span-6 sm:col-span-3">
  
                        <div class="mb-3">
                          <%= form.label :subtitle,  content_tag(:span, "*", style: "color: red;") + '副標題', class:"block mb-2 text-base font-medium text-gray-900 dark:text-white"  %>
                          <%= form.text_field :subtitle, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", 
                          required: true %>
                        </div>
                      </div>
        
                      <div class="col-span-6 sm:col-span-3">
                        <%= form.label :venue,  content_tag(:span, "*", style: "color: red;") + '活動場地', class:" block mb-2 text-base font-medium text-gray-900 dark:text-white"%>
                        <%= form.text_area :venue, class: " resize-none bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", 
                        required: true %>
                      </div>                    
                      <div class="col-span-6 sm:col-span-3">
                        <%= form.label :description, content_tag(:span, "*", style: "color: red;") +  '活動簡述' , class:"block mb-2 text-base font-medium text-gray-900 dark:text-white"%>
                        <%= form.text_area :description, class: "resize-none bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", 
                        required: true %>
                      </div>
        
                      <div class=" col-span-6 sm:col-span-3">
                        <div class="mb-3">
                          <%= form.label :start_at, content_tag(:span, "*", style: "color: red;") +  '活動開始日期', class:"block mb-2 text-base font-medium text-gray-900 dark:text-white"%>
                          <%= form.datetime_field :start_at , class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", 
                          required: true %>
                        </div>
                      </div>                    
                      <div class=" col-span-6 sm:col-span-3">
  
                        <div class="mb-3">
                          <%= form.label :end_at, content_tag(:span, "*", style: "color: red;") +  '活動結束日期', class:"block mb-2 text-base font-medium text-gray-900 dark:text-white"%>
                          <%= form.datetime_field :end_at, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", 
                          required: true %>
                        </div>
                      </div>
                      <div class="col-span-6 sm:col-span-3 items-center my-auto">
                        <%=form.label :address, content_tag(:span, "*", style: "color: red;") + "禮品收件地址", class: "block mb-2 text-base font-medium text-gray-900 dark:text-white"%>
                        <%=form.text_field :address , class: " bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" , require: true%>
                      </div>

                      <div class="col-span-6 sm:col-span-3 items-center my-auto">
                        <%=form.label :phone, content_tag(:span, "*", style: "color: red;") + "收件人電話", class: "block mb-2 text-base font-medium text-gray-900 dark:text-white"%>
                        <%=form.text_field :phone , class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" , require: true%>
                      </div>

                      <div class="col-span-6 sm:col-span-3 items-center my-auto">
                        <%=form.label :receiver, content_tag(:span, "*", style: "color: red;") + "收件人姓名", class: "block mb-2 text-base font-medium text-gray-900 dark:text-white"%>
                        <%=form.text_field :receiver , class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" , require: true%>
                      </div>

                      <div class="col-span-6 sm:col-span-3 items-center my-auto">
                        <%=form.label :avatar,content_tag(:span, "*", style: "color: red;") + "上傳活動封面", class: "block mb-2 text-base font-medium text-gray-900 dark:text-white"%>
                        <%=form.file_field :avatar , class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", require: true%>
                      </div>

                      <div class="col-span-6 sm:col-span-3">
                        <%= image_tag url_for(@event.avatar), class: "img-fixed rounded mx-auto" if @event.avatar.attached? %>
                      </div>
                    </div>
                  </div>
                  <div class="px-4 py-3 bg-gray-50 text-right sm:px-6 flex justify-center">
                    <button type="submit" class="theme-button">
                      新 增
                    </button>
                  </div>
                </div>
              <% end  %>
            </div>
          </div>
              
        </div>
      </section>
      

      


      

app/views/events/show.html.erb
<section class="flex flex-wrap justify-center md:mt-0">
  <div class="flex justify-evenly flex-wrap w-full items-center bg-gradient md-bg-gradient md:shadow-xl py-10">
    <div class="w-full md:w-2/5 lg:mb-0 mb-5 md:mb-0 flex justify-center">
        <%= image_tag @event.avatar, class: "rounded-2xl big_cover2_img shadow-2xl"  if @event.avatar.attached? %>
    </div>

    <div class="w-3/4 md:w-1/3 p-3">
      <h1 class="mb-3 text-4xl md:text-5xl xl:text-5xl font-bold tracking-tight text-theme_light_purple text-center">
        <%= @event.title %>
      </h1>
      <h2 class="font-bold text-3xl my-2 text-center py-2">
        <%= @event.subtitle %>
      </h2>

      <div class="text-center md:text-left">
        <strong class="block text-lg my-1">
          活動內容：
        </strong>
        <p class="break-words my-3 md:pl-3"><%= @event.description %></p>
      </div>

      <div class="text-center md:text-left ">
        <strong class="block text-lg my-1">
          活動地點：
        </strong>
        <span class=" break-words block my-3 md:pl-3"><%= @event.venue %></span>
      </div>

      <div class="text-center md:text-left ">
        <div>
          <strong class="block md:inline-block ">活動開始時間：</strong>
          <%= @event.start_at.strftime("%Y-%m-%d-%H:%M") %>
        </div>
        <div class="py-2">
          <strong class="block md:inline-block ">活動結束時間：</strong>
          <%= @event.end_at.strftime("%Y-%m-%d-%H:%M") %>
        </div>
      </div>
            
      <div class="w-full flex flex-wrap md:justify-start justify-center">

        <% if @event.user == current_user %>
          <%= link_to "前往選擇禮物", stores_event_path(@event.id), class: "theme-button" %>
          <%= link_to "編輯活動", edit_event_path(@event), class: "success-button" %>
          <div class="w-full flex my-3 justify-center md:justify-start">
            <button data-action="click->clipboard#copy" data-controller="clipboard" class="cursor-pointer text-sm text-purple-600 font-semibold rounded-full p-2 border-2 border-purple-200 hover:text-white hover:bg-purple-600 hover:border-transparent inline-block">複製活動連結</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>
  <div class="mx-auto border-theme_blue w-1/2 border-b-2 my-10"></div>
  <h2 class="text-3xl font-bold leading-tight tracking-tight text-center text-theme_text4 dark:text-white mb-5">我的許願清單</h2>
  
  <div class=" mx-auto flex gap-10 flex-wrap justify-center px-3 pt-8 pb-3">
    <% @event_products.each do |event_product| %>
      <div class="rounded-lg shadow-lg bg-white max-w-sm w-72">
          <%= image_tag event_product.avatar, class: "rounded-t-lg img-fixed" if event_product.avatar.attached? %>
        <div class="p-6">
          <h5 class="text-gray-900 text-center text-xl font-medium mb-2">
            <%= event_product.name %>
          </h5>
          <p class="text-gray-700 text-base mb-4 break-words">
            <%= event_product.description %>
          </p>
          <p class="text-gray-700 text-base mb-4">
            <span class="font-bold">NTD. </span><%= event_product.price %>
          </p>
          <div class="flex justify-center">
            <% if @event.user == current_user %> 
              <%= link_to '移除禮物', event_event_product_path(@event, event_product) , method: "delete", data:{ confirm: "確定刪除禮物嗎？"} ,class: "destroy-btn"%> 
            <% else %>
            <%if @product_paid.include?(event_product.id)%>
            <%="已付款"%>
          <% else %>
            <%=link_to "前往結賬",event_product_buy_path(@event, event_product), class: "success-button" %>
          <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>