config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'home', to: 'pages#home'
  get 'sign_in_session', to: 'pages#sign_in_session'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end

  resources :orders, only: [:create] do
    member do
      get :checkout
    end
    collection do
      post :pay
    end
  end

  resources :events, only: [] do
    resources :products, only: [] do
      get :buy
    end
  end

  resources :events do
    resources :event_products, only: [:destroy]
    member do
      patch :add_gift
    end
  end

  resources :events do
    member do
      get :stores, to: 'stores#index', as: 'stores'
    end
  end

  resources :events, only: [] do
    resources :stores, only: [] do
      resources :products
    end
  end

  resources :stores do
    resources :products
    member do
      get :orders, to: 'stores#orders'
    end
  end
end

app/controllers/stroes_controller.rb
class StroesController < ApplicationController
end

app/helpers/stroes_helper.rb
module StroesHelper
end

app/views/stroes/edit.html.erb
<h1>編輯 商店資訊</h1>

<%= form_with model:@store do |f| %>
    <div>
        <%= f.label '商品名稱' %>
            <%= f.text_field :title %>
    </div>
    <div>
        <%= f.label '商品描述' %>
            <%= f.text_area :description , size: "30 x 2" %>
    </div>
    <div>
        <%= f.submit %>
    </div>
    <% end %>

app/views/stroes/index.html.erb
<div style="background-color: green; color: white">
    <%= notice %>
</div>

<h1>我的商店</h1>

<div style="background-color: red; color: white">
    <%= alert %>
</div>

<hr>

<nav>
    <%= link_to '新增商店' , new_store_path %>
</nav>

<hr>

<table>
    <tr>
        <td></td>
        <td>商店名稱</td>
        <td>商店描述</td>
        <td>編輯商店</td>
        <td>刪除商店</td>
    </tr>

    <% @store.each do |store| %>
        <tr>
            <td></td>
            <td>
                <%= link_to store.title, store_path(store.id) %>
            </td>
            <td>
                <%= store.description %>
            </td>
            <td>
                <%= link_to '編輯資訊' , edit_store_path(store.id) %>
            </td>
            <td>
                <%= link_to '刪除商店' , store_path(store.id), method: 'delete' , data: {confirm: '確定要刪除嗎？' } %>
            </td>
        </tr>
        <% end %>
</table>

app/views/stroes/new.html.erb
<h1>建立我的商店</h1>


<%= form_with model:@store do |f| %>
    <div>
        <%= f.label '商店名稱' %>
            <%= f.text_field :title %>
    </div>
    <div>
        <%= f.label '商店描述' %>
            <%= f.text_area :description , size: "30 x 2" %>
    </div>
    <div>
        <%= f.submit %>
    </div>
    <% end %>