config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'home', to: 'pages#home'
  get 'sign_in_session', to: 'pages#sign_in_session'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end

  resources :orders, only: [:create] do
    member do
      get :checkout
    end
    collection do
      post :pay
    end
  end

  resources :events, only: [] do
    resources :products, only: [] do
      get :buy
    end
  end

  resources :events do
    resources :event_products, only: [:destroy]
    member do
      patch :add_gift
    end
  end

  resources :events do
    member do
      get :stores, to: 'stores#index', as: 'stores'
    end
  end

  resources :events, only: [] do
    resources :stores, only: [] do
      resources :products
    end
  end

  resources :stores do
    resources :products
    member do
      get :orders, to: 'stores#orders'
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  acts_as_paranoid
  # validate
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :stock, presence: true

  # relation
  has_one_attached :avatar
  has_many :event_products, dependent: :destroy
  has_many :events, through: :event_products
  has_many :product_orders, dependent: :destroy
  has_many :orders, through: :product_orders
  belongs_to :store
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: %i[index show edit destroy]
  before_action :find_store, only: %i[index create edit update new]
  before_action :authenticate_user!

  def index
    @event = Event.find(params[:event_id]) if current_user?
    @products = @store.products
  end

  def new
    @product = current_user.store.products.new
  end

  def create
    @product = current_user.store.products.new(product_params)
    if @product.save
      redirect_to store_products_path, notice: '成功新增商品'
    else
      render :new
    end
  end

  def show; end

  def edit
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to store_products_path, notice: '已刪除商品'
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to store_products_path, notice: '成功更新商品'
    else
      render :edit
    end
  end

  def buy
    @product = Product.find(params[:product_id])
    @event = Event.find(params[:event_id])
  end

  private

  def find_product
    @product = Product.find_by(id: params[:product_id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :stock, :avatar, :store_id)
  end

  def find_store
    @store = Store.find_by(id: params[:store_id])
  end 
end

app/views/products/buy.html.erb
<div class="container px-6 pt-14 mx-auto flex items-center justify-center lg:h-full md:w-2/4">
  <%= form_with(url: orders_path, method: 'post', data: { controller: "order-quantity" }) do |f| %>
    <div class="my-2 flex justify-center flex-wrap rounded-md shadow-xl">
      <h1 class="py-3 bg-theme_light_purple w-full text-center text-white text-3xl font-bold rounded-t-md">
        產品名稱：<%= @product.name %>
      </h1>
      <p class="w-full text-center my-2 text-2xl font-bold">
        描述：<%=@product.description %>
      </p>
      <p class="w-full text-center my-1 text-2xl font-bold">
        庫存：<%=@product.stock%>
      </p>
      <div class="flex justify-center w-full">
        <%= f.hidden_field :product_id, value: @product.id %>
        <%= f.hidden_field :event_id, value: @event.id %>
        <button data-action="click->order-quantity#decrement" class="text-5xl font-bold px-5">-</button>
        <%= f.number_field :quantity, value: 1, min: 1, max: @product.stock, data: { order_quantity_target: "quantity" },class:"border-0 text-xl text-center " %>
        <button data-action="click->order-quantity#increment" class="text-5xl font-bold px-5">+</button>
      </div>
      <div data-controller="order-amount" data-price="<%= @product.price %>" data-action="update-quantity@document->order-amount#updateQuantity" class="w-full">
        <div class="text-center my-4 text-2xl font-bold">
          單價：<%= @product.price %>元
        </div>
        <div class="text-center my-4 text-2xl font-bold">
          小計：<span data-order-amount-target="amount"></span>元
        </div>
      </div>
      <%= f.hidden_field :receiver, value: @event.receiver %>
      <p class="w-full text-center font-bold text-base mb-1">
        收件人姓名 : 
        <span class="font-normal text-theme_text4"><%= @event.receiver%></span>  
      </p>
      <%= f.hidden_field :address, value: @event.address %>
      <p class="w-full text-center font-bold text-base mb-1"> 收件人地址 : 
        <span class="font-normal text-theme_text4"><%= @event.address%></span>
      </p>
      <%= f.hidden_field :phone, value: @event.phone %>
      <p class="w-full text-center font-bold text-base mb-1"> 收件人電話 : 
        <span class="font-normal text-theme_text4"> <%= @event.phone%></span>
      </p>
      <%= f.submit '結帳', class: 'theme-button cursor-pointer mb-6 mt-3' %>
    </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<section class="h-full ">
  <div class="container px-6 mb-3 pt-14 mx-auto flex items-center justify-center lg:h-full ">
    <div class="flex justify-center items-center flex-wrap g-6 text-gray-800 ">
      <div class="mt-5 md:mt-0 md:col-span-2 ">
        <%=form_with(model: @product, url: store_product_path, method: 'patch') do |f| %>
          <div class="shadow-xl overflow-hidden rounded-md ">
            <div class="px-4 py-3 bg-theme_light_purple text-right sm:px-6 flex justify-center rounded-t">
              <h1 class=" text-white text-2xl font-bold leading-tight tracking-tight text-center  md:text-3xl dark:text-white ">
                編 輯 商 品
              </h1>
            </div>
            <div class="px-4 py-5 bg-white sm:p-6">
              <div class="grid grid-cols-6 gap-6 ">
                <div class="col-span-6 sm:col-span-3">
                  <%= f.label :name, '商品名稱', autofocus: true, 
                  class:"block mb-2 text-base font-medium text-gray-900 dark:text-white" %>
                  <%=f.text_area :name, class: "resize-none bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" ,
                  required: true%>
                </div>
  
                <div class=" col-span-6 sm:col-span-3">

                  <div class="mb-3">
                    <%=f.label :description, "商品敘述", class: "block mb-2 text-base font-medium text-gray-900 dark:text-white font-bold" %>
                    <%=f.text_area :description, class: " resize-none bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"%>
                  </div>
                </div>
  
                <div class=" col-span-6 sm:col-span-3">

                  <div class="mb-3">
                    <%= f.label :price, '商品價格', class:"block mb-2 text-base font-medium text-gray-900 dark:text-white"%>
                    <%=f.text_field :price, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" ,
                    required: true%>
                  </div>
                </div>

                <div class=" col-span-6 sm:col-span-3">

                  <div class="mb-3">
                    <%= f.label :stock, '庫存量', class:"block mb-2 text-base font-medium text-gray-900 dark:text-white"  %>
                    <%=f.text_field :stock, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" ,
                    required: true%>
                  </div>
                </div>
                <div class="col-span-6 sm:col-span-3 pt-5">
                  <%=f.label :avatar,"更換圖片（無需更換請點擊完成編輯）", class: "block mb-2 text-base font-medium text-gray-900 dark:text-white font-bold"%>
                  <%=f.file_field :avatar, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 mb-5"%>
                </div>   
                <div class="col-span-6 sm:col-span-3">
                  <%= image_tag @product.avatar, class: "rounded mx-auto img-fixed" if @product.avatar.attached?  %> 
                </div>                 
              </div>
            </div>
            <div class="px-4 pb-3 py-3 bg-gray-50 text-right sm:px-6 flex justify-center">
              <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-base font-medium rounded-md text-white bg-theme_light_purple hover:bg-theme_dark_purple">
                完 成 編 輯
              </button>
            </div>
          </div>
        </div>
        <% end %>
    </div>

  </div>
</section>

app/views/products/index.html.erb
<div class="pt-10">
  <!-- 商店資訊 -->
  <section>
    <div class="flex flex-col items-center justify-center">
      <div>
        <%if @store.avatar.attached?%>
          <img src="<%=(url_for(@store.avatar))%>" class="rounded align-center big_cover_img"/>
        <%end %>
      </div>
      <span class="text-3xl text-center font-bold mt-10 w-8/12 break-words">
        <%= @store.title %>
      </span>
      <span class="my-5 text-base text-center w-6/12 break-words">
        <%= @store.description %>
      </span>
    </div>
  </section>
  
  <!-- 功能列按鈕 -->
  <% if current_user.role == 'vendor' %>
    <div class="flex bg-gray-100 w-full justify-center flex-wrap">
      <%= link_to '編輯商店資訊' , edit_store_path(@store.id) ,class:"theme-button md:mx-6"%>
      <%= link_to '訂單查詢' , orders_store_path(@store.id),class:"theme-button md:mx-6" %>
      <%= link_to '新增商品' , new_store_product_path(@store.id) ,class:"theme-button md:mx-6" %>
    </div>
  <% end %>

  <div class="mx-auto border-theme_blue w-1/2 border-b-2 mb-10"></div>


<!-- 商品列表 -->
<h2 class="text-center text-3xl font-bold text-theme_text4">商品列表</h2>
  <div class=" mx-auto flex gap-10 flex-wrap justify-center px-3 pt-8  pb-3">
    <% @products.each do |product| %>
      <div class="bg-white shadow-md border-gray-200 rounded-lg w-72">
          <%if product.avatar.attached?%>
            <img src="<%=(url_for(product.avatar))%>" class="rounded-t align-center img-fixed"/>
          <%end%>
        <div class=" mt-2">
          <h1 class="text-center text-theme_text5 font-bold text-2xl tracking-tight mb-2 break-words px-2">
            <%= product.name %>
          </h1>
          <p class="text-base text-theme_text5 mb-3 px-3">
            <span class="font-bold">商品介紹：</span>
            <div class="mb-3 px-5 break-words"><%= product.description %></div>
          </p>
          <p class="text-base text-theme_text5 mb-3 px-3">
            <span class="font-bold ">NTD. </span><%= product.price %>
          </p>
          <p class="text-sm text-theme_text3 mb-3 px-3">
            <span class="font-bold">庫存量：</span><%= product.stock %>
          </p>
          <% if current_user.role == 'vendor'%>
            <div class="mb-3 text-center">
              <%= link_to '編輯商品' , edit_store_product_path(@store,product) ,class:"theme-button"%>
              <%= link_to '刪除商品' , store_product_path(@store, product), method: 'DELETE' , data: {confirm: "確定嗎" } ,class:"destroy-btn"%>
            </div>
          <% end %>
          <% if current_user.role == 'user'  %>
            <div class="flex justify-center mb-3">
              <% if @event.products.include?(product) %>
                <button
                data-controller="add-gift"
                data-action="click->add-gift#toggle"
                data-event-id="<%= @event.id%>"
                data-product-id="<%= product.id %>"
                class="success-button">已加入禮物</button>
              <% else %>
                <button
                data-controller="add-gift"
                data-action="click->add-gift#toggle"
                data-event-id="<%= @event.id%>"
                data-product-id="<%= product.id %>"
                class="theme-button">加入禮物</button>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<section class="h-screen ">
  <div class="container px-6 pt-14 mx-auto flex items-center justify-center lg:h-full "">
    <div class="flex justify-center items-center flex-wrap g-6 text-gray-800 ">
      <div class="mt-5 md:mt-0 md:col-span-2 ">
        <%=form_with(model: @product, url: store_products_path(@store.id), method: 'post') do |f| %>
          <div class="shadow-xl overflow-hidden rounded-md ">
            <div class="px-4 py-3 bg-theme_light_purple text-right sm:px-6 flex justify-center rounded-t">
              <h1 class=" text-white text-2xl font-bold leading-tight tracking-tight text-center  md:text-3xl dark:text-white ">
                新 增 商 品
              </h1>
            </div>
            <div class="px-4 py-5 bg-white sm:p-6">
              <div class="grid grid-cols-6 gap-6 ">
                <div class="col-span-6 sm:col-span-3">
                  <%= f.label :name, content_tag(:span, "*", style: "color: red;") + '商品名稱', autofocus: true, 
                  class:"block mb-2 text-base font-medium text-gray-900 dark:text-white" %>
                  <%=f.text_area :name, class: "resize-none bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" ,
                  required: true%>
                </div>
  
                <div class=" col-span-6 sm:col-span-3">

                  <div class="mb-3">
                    <%=f.label :description, content_tag(:span, "*", style: "color: red;") + "商品敘述", class: "block mb-2 text-base font-medium text-gray-900 dark:text-white font-bold" %>
                    <%=f.text_area :description, class: " resize-none bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"%>
                  </div>
                </div>
  
                <div class=" col-span-6 sm:col-span-3">

                  <div class="mb-3">
                    <%= f.label :price, content_tag(:span, "*", style: "color: red;") + '商品價格', class:"block mb-2 text-base font-medium text-gray-900 dark:text-white"%>
                    <%=f.text_field :price, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" ,
                    required: true%>
                  </div>
                </div>

                <div class=" col-span-6 sm:col-span-3">

                  <div class="mb-3">
                    <%= f.label :stock, content_tag(:span, "*", style: "color: red;") + '庫存量', class:"block mb-2 text-base font-medium text-gray-900 dark:text-white"  %>
                    <%=f.text_field :stock, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" ,
                    required: true%>
                  </div>
                </div>
                <div class="col-span-6 sm:col-span-3">
                  <%=f.label :avatar,content_tag(:span, "*", style: "color: red;") + "產品照片上傳", class: "block mb-2 text-base font-medium text-gray-900 dark:text-white font-bold"%>
                  <%=f.file_field :avatar, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 mb-5", required: true%>
                </div>                    
              </div>
            </div>
            <div class="px-4 py-3 bg-gray-50 text-right sm:px-6 flex justify-center">
              <button type="submit" class="theme-button">
                確 定 新 增
              </button>
            </div>
          </div>
        <% end  %>
      </div>
    </div>

  </div>
</section>

app/views/products/show.html.erb
<h1>產品資料</h1>
<h2><%= @product.name %></h2>
  <%if @product.avatar.attached?%>
    <img src="<%=(url_for(@product.avatar))%>">
  <%end%>
  <ul>
    <li>產品描述:<%=@product.description%></li>
    <li>產品價格:<%=@product.price%></li>
    <li>庫存<%=@product.stock%></li>
  </ul>